### ISSUE TITLE
Aξιολόγηση από ομότιμους

### ISSUE THREAD

**Issue by diogenisAl** [ioniodi/D3js-uk-political-donations#18]

**Comment by diogenisAl** [comment]
Ναι, εν μέρει. Να τονίσω ότι σύμφωνα με τις οδηγίες [εδώ](https://github.com/courses-ionio/projects), στην ομότιμη αξιολόγηση θα συμμετάσχουν όσοι/ες έχουν υλοποιήσει πλήρως όλα τα ζητούμενα:

> Σε αυτό το παραδοτέο συμμετέχουν μόνο όσοι έχουν καταθέσει εμπρόθεσμα όλα τα υποερωτήματα και για τα δύο προηγούμενα παραδοτέα

**Comment by DimitrisTria** [comment]
Στις οδηγίες στο κομμάτι πριν το σχολιασμό για αδυναμίες και προτάσεις για βελτιώσεις, εμφανίζονται κάποια κουτάκια τα οποία μοιάζουν με checkboxes. Θέλετε στα κομμάτια που έχουν ολοκληρωθεί να κάνουμε check το κουτάκι ή να γράψουμε κάτι σχετικά με αυτό;

**Comment by diogenisAl** [comment]
@DimitrisTria ανέβασε εδώ αν μπορείς το link με τις οδηγίες στις οποίες αναφέρεσαι για να σου απαντήσω πιο συγκεκριμένα

**Comment by DimitrisTria** [comment]
link με τις οδηγίες για την ομότιμη αξιολόγηση: https://courses-ionio.github.io/help/review/

**Comment by diogenisAl** [comment]
@DimitrisTria το πιο σημαντικό είναι να γράψεις κάτι για κάθε ένα από αυτά.
