### ISSUE TITLE
Παραδοτέο 1 potential conflicts

### ISSUE THREAD

**Issue by DimosPagakis** [ioniodi/D3js-uk-political-donations#22]
Θέλω να ρωτήσω, εφόσον όλες οι αλλαγές θα γίνουν στο αποθετήριο μας (αυτές για το visualization αλλά και για το .csv αρχείο), πώς θα γίνει το pull request για το τελευταίο χωρίς να επηρεαστεί και ο κώδικας στο δικό σας αποθετήριο; Γιατί αν δεν κάνω λάθος στο pull request θα περιέχονται όλα, κάτι που δεν είναι επιθυμητό. Σωστά;

**Comment by diogenisAl** [comment]
@DimosPagakis Θα πρέπει κάθε αλλαγή που ενδεχομένως να προκαλέσει conflict να γίνεται σε δικό της κλαδί (branch)

**Comment by DimosPagakis** [comment]
@diogenisAl Οι αλλαγές όμως στον κώδικα του visualization πρέπει να γίνουν στο μάστερ, από ότι κατάλαβα διαβάζοντας το documentation. Ακόμα και αν κάνω σε branch τις αλλαγές για το .csv πχ, πάλι θα υπάρξει σύγκρουση. Έχω καταλάβει σωστά;

**Comment by diogenisAl** [comment]
@DimosPagakis 
Σύμφωνα με τις [γενικές οδηγίες](https://github.com/courses-ionio/help/blob/master/guide/index.md) οδηγίες που ισχύουν σε όλες τις εργασίες: "Δημιουργία κλαδιού (branch) στο -αντιγραμμένο στον λογαριασμό σας- αποθετήριο (repository) εφαρμογής με τίτλο "develop" στο οποίο μπορείτε ελεύθερα να κάνετε δοκιμές και να το σβήνετε χωρίς να πειράξετε το "master" το οποίο θέλετε να είναι καθαρό για πιθανό συγχρονισμό με το αρχικό".
Πιο ειδικά στη συγκεκριμένη άσκηση, αν έχεις ένα καθαρό (=χωρίς αλλαγές σε σχέση με το αρχικό αποθετήριο) branch, στο οποίο η μοναδική αλλαγή σε σχέση με το αρχικό master είναι η προσθήκη του csv αρχείου σου και κάνεις pull request προς το κεντρικό αποθετήριο του κώδικα/άσκησης, τότε δεν θα υπάρχει σύγκρουση στο κεντρικό αποθετήριο.

Προτείνω να έχεις ένα "καθαρό" branch του αρχικού αποθετηρίου για κάθε προσθήκη (pull request) που θέλεις να κάνεις στο κεντρικό αποθετήριο του κώδικα/άσκησης.
