### ISSUE TITLE
Προθεσμία παράδοσης εργασιών

### ISSUE THREAD

**Issue by kikh** [ioniodi/D3js-uk-political-donations#348]
Μέχρι πότε πρέπει να έχουμε παραδόσει τις εργασίες; (Για εξεταστική Σεπτεμβρίου)

**Comment by diogenisAl** [comment]
Οδηγίες για τις εργασίες και για την εξεταστική του Σεπτεμβρίου υπάρχουν εδώ: [https://github.com/courses-ionio/help](https://github.com/courses-ionio/help)
