### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by petros1997** [ioniodi/D3js-uk-political-donations#46]
Έχω επιλέξει εικόνες για τους εξής δωρητές:
1) Shore Capital Group --603
2) Saatchi and Saatchi Group --786
3) Lycamobile UK --600
4) Joseph Powntree Reform Trust --820
5)C and C Group --823

**Comment by diogenisAl** [comment]
Για να δηλώσεις ποιες φωτογραφίες θα ανεβάσεις, θα πρέπει να γράψεις σχόλιο [εδώ](https://github.com/ioniodi/D3js-uk-political-donations/issues/16), όχι να ξεκινήσεις νέο issue.
